name: CI Pipeline

# Disparadores del workflow
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

# Definición de jobs
jobs:
  build:
    runs-on: ubuntu-latest  # Entorno de ejecución

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python (si es necesario para backend en Python)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Asegúrate de usar la versión que necesites

      # 3. Instalar dependencias (Python)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener un archivo de requisitos

      # 4. Ejecutar pruebas
      - name: Run tests
        run: |
          pytest  # Ejecuta los tests (puedes ajustar según el framework)

      # 5. Linting (opcional para asegurar clean code)
      - name: Lint code
        run: |
          pip install flake8
          flake8 .  # Ejecuta flake8 en todo el proyecto para verificar el estilo de código
